projects:
  DoublesMemberGenerator:
    schemaPath: amplify/backend/api/DoublesMemberGenerator/build/schema.graphql
    includes:
      - src/api/graphql/**/*.ts
    excludes:
      - ./amplify/**
      # https://github.com/aws-amplify/amplify-codegen/issues/734
      - src/api/graphql/index.ts
      - src/api/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/API.ts
        docsFilePath: src/api/graphql
        maxDepth: 4
extensions:
  amplify:
    version: 3
