projects:
  DoublesMemberGenerator:
    schemaPath: amplify/backend/api/DoublesMemberGenerator/build/schema.graphql
    includes:
      - packages/api/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      # https://github.com/aws-amplify/amplify-codegen/issues/734
      - packages/api/src/graphql/index.ts
      - packages/api/src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: packages/api/src/API.ts
        docsFilePath: packages/api/src/graphql
        maxDepth: 4
extensions:
  amplify:
    version: 3
