services:
  app:
    image: public.ecr.aws/docker/library/node:20
    working_dir: /app/server
    volumes:
      - ./dist:/app:ro
    command: node index.mjs
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - 3000:3000
    tty: true

volumes:
  node_modules: {}
