/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_appsync_graphqlEndpoint:
    "https://irjds45ffzbk5clrmqfhyoem6q.appsync-api.ap-northeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-northeast-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-kzsgeo7qzbacrijyqp7kynrd54",
};

export default awsmobile;
